@startchen
left to right direction

entity Refugio {
  Localizacion <<key>>
  Nombre
  Telefono
  Email
  Horario
}

entity Persona {
  DNI <<key>>
  Nombre_Completo
  Telefono
  Direccion
  Email
}

entity Adoptante {
  Aptitud_Adop
}

entity Empleado {
  Rol
  Puesto
  Sueldo
  Expediente_Academico
}

entity Animal {
  Alias <<key>>
  Especie
  Nombre
  Sexo
}

entity Corral {
  Id_Corral <<key>>
}

entity Adopcion {
  Num_Adopcion <<key>>
  Estado
  Fecha
}

entity Devolución {
  Plazo
  Motivo
}

relationship Registra {
}

relationship Incluye {
}

relationship Situado {
}

relationship Solicita {
}

relationship Contiene {
}

relationship Contrata {
}

Persona -- Empleado
Persona -- Adoptante

Refugio -- Registra
Registra -- Animal

Refugio -- Contrata
Contrata -- Empleado

Animal -- Situado
Situado -- Corral

Adopcion -- Incluye
Incluye -- Animal

Adopcion -- Contiene
Contiene -- Devolución

Adoptante -- Solicita
Solicita -- Adopcion

@endchen