@startuml
title Diagrama de Clases - Refugio "Mi Huella" 


left to right direction


class Persona {
  - DNI : int
  - Nombre_Completo : string
  - Direccion : string
  - Telefono : int
  - Email : string
}

class Adoptante {
  - Aptitud_Adop : string

  + SolicitarAdopcion(alias : string) : Adopcion
  + EjecutarArrepentimiento(numAdopcion : int, motivo : string, plazo : string) : void
}

class Empleado {
  - Puesto : string
  - Sueldo : float
  - Rol : string
  - Expediente_Academico : string
}

class Refugio {
  - Nombre : string
  - Localizacion : string
  - Telefono : int
  - Email : string
  - Horario : string

  + RegistrarAnimal(alias : string, especie : string, nombre : string, sexo : string) : Animal
  + RegistrarEmpleado(dni : int, nombre : string, puesto : string, rol : string, expediente : string, direccion : string, telefono : int, email : string) : Empleado
  + RegistrarAdopcion(adoptante : Adoptante, animal : Animal, fecha : Date) : Adopcion
}

class Corral {
  - Id_Corral : int
}

class Animal {
  - Alias : string
  - Especie : string
  - Nombre : string
  - Sexo : string
}

class Adopcion {
  - Num_Adopcion : int
  - Fecha : Date
  - Estado : string

  + getEstado() : string
  + actualizarEstado(estado : string) : void
  + crearDevolucion(plazo : string, motivo : string) : Devolucion
  + ConsultarEstadoAdopcion() : string
}

class Devolucion {
  - Plazo : string
  - Motivo : string
}


Persona <|-- Adoptante
Persona <|-- Empleado


Refugio "1" *-- "1..*" Animal : Registra
Refugio "1" -- "1..*" Empleado : Contrata

Corral "1" -- "0..*" Animal : aloja

Adoptante "1" -- "0..*" Adopcion : solicita
Adopcion "1" -- "1" Animal : incluye

Adopcion "1" *-- "0..1" Devolucion : puede generar

@enduml
