@startuml
' Diagrama ER de adopciones

entity ADOPTANTE {
  Nombre
  Direccion
  Telefono
  Aptitud_Adop
}

entity REFUGIO {
  Nombre
  Direccion
}

entity ANIMAL {
  *id
  Tipo
  Nombre
  Corral {
    IdCorral
}

entity ADOPCION {
  Estado
  Devolucion {
    Plazo
}

' Relaciones
ADOPTANTE ||--|| ADOPCION : solicita
REFUGIO ||--|| ANIMAL : registra
ADOPCION ||--|| ANIMAL : incluye

@enduml

![Diagrama de adopciones](images/plantuml.png)
