@startchen
left to right direction

entity Refugio {
  Localizacion <<PK>>
  Nombre
  Telefono
  Email
  Responsable
  Horario
}

entity Adoptante {
  DNI <<PK>>
  Nombre_Completo
  Telefono
  Direccion
  Email
  Aptitud_Adop
}

entity Empleado {
  DNI <<PK>>
  Nombre_Completo
  Telefono
  Direccion
  Email
  Rol
  Puesto
  Sueldo
  Expediente_Academico
  Aptitud_Adop
}

entity Animal {
  Alias <<PK>>
  Especie
  Nombre
  Sexo
}

entity Corral {
  Id_Corral <<PK>>
}

entity Adopcion {
  Num_Adopcion <<PK>>
  Estado
  Fecha
}

entity Devolución {
  Plazo
  Motivo
}

relationship Registra {
}

relationship Incluye {
}

relationship Situado {
}

relationship Solicita {
}

relationship Contiene {
}

relationship Contrata {
}

relationship Puede_Solicitar {
}

relationship Evalua {
}

Refugio -- Registra
Registra -- Animal

Refugio -- Contrata
Contrata -- Empleado

Animal -- Situado
Situado -- Corral

Adopcion -- Incluye
Incluye -- Animal

Adopcion -- Contiene
Contiene -- Devolución

Adoptante -- Solicita
Solicita -- Adopcion

Empleado -- Puede_Solicitar
Puede_Solicitar -- Adopcion

Refugio -- Evalua
Evalua -- Adopcion

@endchen